-- Database Schema for Solo Leveling Fitness App (Supabase Version)

-- NOTE: Run this in the Supabase SQL Editor

-- 1. Profiles Table (Extends Supabase Auth)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  email text,
  
  -- Hunter Stats
  hunter_class text DEFAULT 'Civilian',
  rank text DEFAULT 'E',
  level int DEFAULT 1,
  experience_points int DEFAULT 0,

  -- Physical Stats
  age int,
  weight_kg numeric,
  height_cm int,
  activity_level text,
  goal text,

  -- Stats meant for future use
  strength int DEFAULT 10,
  agility int DEFAULT 10,
  vitality int DEFAULT 10,

  constraint username_length check (char_length(username) >= 3)
);

-- Enable RLS for Profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

-- (Optional) If you want to allow users to update their own profile later
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. Exercises Table
CREATE TABLE exercises (
    exercise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    muscle_group text not null,
    rank text check (rank in ('E', 'D', 'C', 'B', 'A', 'S')) not null,
    type text check (type in ('Strength', 'Cardio', 'Stamina', 'Explosive', 'Speed', 'Static')) not null,
    location text check (location in ('Home', 'Gym', 'Both')) default 'Both',
    image_url text,
    video_url text,
    instructions text
);

-- Enable RLS for Exercises
alter table exercises enable row level security;

create policy "Exercises are viewable by everyone."
  on exercises for select
  using ( true );

-- 3. Routines Table (Daily Quests)
CREATE TABLE routines (
    routine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid references auth.users on delete cascade not null,
    date_generated DATE DEFAULT CURRENT_DATE,
    is_completed BOOLEAN DEFAULT FALSE,
    title TEXT,
    penalty TEXT
);

-- Enable RLS for Routines
alter table routines enable row level security;

create policy "Users can view their own routines."
  on routines for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own routines."
  on routines for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own routines."
  on routines for update
  using ( auth.uid() = user_id );

-- 4. Routine Exercises (Junction Table)
CREATE TABLE routine_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id BIGINT REFERENCES routines(routine_id) ON DELETE CASCADE,
    exercise_id BIGINT REFERENCES exercises(exercise_id) ON DELETE CASCADE,
    sets INT,
    reps TEXT,
    order_index INT
);

-- Enable RLS for Routine Exercises
alter table routine_exercises enable row level security;

create policy "Users can interact with their own routine exercises."
  on routine_exercises
  using (
    exists (
      select 1 from routines
      where routines.routine_id = routine_exercises.routine_id
      and routines.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from routines
      where routines.routine_id = routine_exercises.routine_id
      and routines.user_id = auth.uid()
    )
  );

-- 5. Performance Logs (Progress Tracker)
CREATE TABLE performance_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid references auth.users on delete cascade not null,
    exercise_id BIGINT REFERENCES exercises(exercise_id) ON DELETE CASCADE,
    date_logged TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    weight_lifted NUMERIC,
    reps_completed INT,
    rpe INT -- Rate of Perceived Exertion (1-10)
);

-- Enable RLS for Logs
alter table performance_logs enable row level security;

create policy "Users can view their own logs."
  on performance_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own logs."
  on performance_logs for insert
  with check ( auth.uid() = user_id );


-- 6. FUNCTION & TRIGGER to handle new user signup
-- This function runs on the server (postgres) when a new-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  score integer := 0;
  calculated_bmi numeric;
  initial_rank text := 'E';
  meta jsonb;
begin
  meta := new.raw_user_meta_data;
  
  -- 1. Activity Score
  IF (meta->>'activity_level') = 'lightly_active' THEN score := score + 10;
  ELSIF (meta->>'activity_level') = 'moderately_active' THEN score := score + 25;
  ELSIF (meta->>'activity_level') = 'very_active' THEN score := score + 45;
  ELSIF (meta->>'activity_level') = 'extra_active' THEN score := score + 70;
  END IF;

  -- 2. BMI Score (Check if simple valid numbers)
  IF (meta->>'weight') IS NOT NULL AND (meta->>'height') IS NOT NULL THEN
      -- Height in meters for BMI
      -- Avoid division by zero just in case
      IF (meta->>'height')::numeric > 0 THEN
          calculated_bmi := (meta->>'weight')::numeric / ((meta->>'height')::numeric / 100)^2;
          
          IF calculated_bmi >= 18.5 AND calculated_bmi <= 25.0 THEN
              score := score + 10;
          ELSIF calculated_bmi > 30.0 OR calculated_bmi < 18.5 THEN
              score := score - 5;
          END IF;
      END IF;
  END IF;

  -- 3. Age Score
  IF (meta->>'age') IS NOT NULL THEN
      IF (meta->>'age')::int < 35 THEN score := score + 5;
      ELSIF (meta->>'age')::int > 50 THEN score := score - 5;
      END IF;
  END IF;

  -- 4. Determine Rank
  IF score > 100 THEN initial_rank := 'A';
  ELSIF score > 70 THEN initial_rank := 'B';
  ELSIF score > 40 THEN initial_rank := 'C';
  ELSIF score > 20 THEN initial_rank := 'D';
  ELSE initial_rank := 'E';
  END IF;

  insert into public.profiles (id, username, email, age, weight_kg, height_cm, activity_level, goal, rank, strength, agility, vitality)
  values (
    new.id,
    coalesce(meta->>'username', new.email),
    new.email,
    (meta->>'age')::int,
    (meta->>'weight')::numeric,
    (meta->>'height')::int,
    meta->>'activity_level',
    meta->>'goal',
    initial_rank,
    10, 10, 10
  );
  return new;
end;
$$;

-- Trigger execution
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
